name: 2K/DENMARK
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68733
title: 2K/DENMARK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#027ea7'
    - '#000001'
    - '#f6951e'
    - '#ec038e'
  brandStrength: 0.75
  lightness: 0.7130273
  saturation: 0.6405869
  rhythmicContrast: 0.7603399
purpose: []
